version: "3.9"
services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - maria_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: password
    volumes:
      - "minio:/data"
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - 9000:9000
      - 9001:9001
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 user password;
      mc mb --ignore-existing minio/images;
      mc anonymous set public minio/images;
      "

volumes:
  maria_data:
  minio:
